### ISSUE TITLE
Possible regression bug on reconnect after RabbitMQ node is disconnected

### ISSUE THREAD

**Issue by seang-es** [logstash-plugins/logstash-output-rabbitmq#13]
We have logstash connect to a load-balancer host that proxies to a pool of backend RabbitMQ hosts.

When we disable one of the backend hosts at the load-balancer, logstash 1.5.0 and logstash 1.5.1 do not reconnect, if they were connected to that post.

If we try same setup with logsatsh 1.3.3 it is able to reconnect.

This is our output block: 
output { 
rabbitmq { 
host => "$LOADBALANCER" 
port => "$PORT" 
exchange => "amq.direct" 
exchange_type => "direct" 
key => "test" 
} 
}

For 1.5.x version, we just get below error message (and it is NOT able to reconnect).

::ChannelAlreadyClosed>, :backtrace=>["/app/infra/working/logstash-1.5.1/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/exceptions.rb:121:in `convert_and_reraise'", "/app/infra/working/logstash-1.5.1/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/channel.rb:965:in `converting_rjc_exceptions_to_ruby'", "/app/infra/working/logstash-1.5.1/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/channel.rb:595:in `basic_publish'", "/app/infra/working/logstash-1.5.1/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/exchange.rb:77:in `publish'", "/app/infra/working/logstash-1.5.1/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-0.1.5-java/lib/logstash/outputs/rabbitmq/march_hare.rb:40:in `publish_serialized'", "org/jruby/RubyProc.java:271:in `call'", "/app/infra/working/logstash-1.5.1/vendor/bundle/jruby/1.9/gems/logstash-codec-json-0.1.7/lib/logstash/codecs/json.rb:44:in `encode'", "/app/infra/working/logstash-1.5.1/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-0.1.5-java/lib/logstash/outputs/rabbitmq/march_hare.rb:31:in `receive'", "/app/infra/working/logstash-1.5.1/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.1-java/lib/logstash/outputs/base.rb:88:in `handle'", "(eval):24:in `output_func'", "/app/infra/working/logstash-1.5.1/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.1-java/lib/logstash/pipeline.rb:243:in `outputworker'", "/app/infra/working/logstash-1.5.1/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.1-java/lib/logstash/pipeline.rb:165:in `start_outputs'"], :level=>:error}

**Comment by andrewvc** [comment]
This looks like it may actually be connected to #12 . I'm going to try and get a fix for that out soon, I think it should fix this issue. It looks like the failure to reset the `@x` instance var on exception is the root cause here.

**Comment by andrewvc** [comment]
@seang-es I've just published a new version of this plugin 1.0.1, can you see if that helps? 

I'm also going to do some significant rework of this gem over the next week.

**Comment by andrewvc** [comment]
@seang-es since I haven't heard back from you I'm going to close this ticket. If you're still having issues please re-open this ticket or open a new issue.
