### ISSUE TITLE
Implement a blocked listener and write warning messages to log

### ISSUE THREAD

**Issue by Fogetti** [logstash-plugins/logstash-output-rabbitmq#14]
I have run into a strange thing. Correct me if I am wrong, you can also immediately close this issue in that case.

So I was sending messages to RabbitMQ with the plugin, but RabbitMQ stopped accepting messages when it was running out of disk space. From that point my whole pipeline got stuck without any apparent reason. I spent a whole day with debugging until I found out that RabbitMQ was the culprit.

On the other hand RabbitMQ offers notifications through listener mechanism.

I was checking the code and this plugin is using MachHare, right? I also checked that MachHare offers a blocked listener as in the example below:
https://github.com/ruby-amqp/march_hare/blob/master/examples/blocked_connection_notifications.rb

Is it possible to implement this? Just write a warning message or something in the logs. It would make us users so much less frustrated.

**Comment by andrewvc** [comment]
@Fogetti sorry to hear about these issues, I'm giving the rabbitmq plugin some TLC over the next week, and I hope to be able to address issues like this. I've got some higher priority bugs I'm tackling right now, but if you could submit a PR that'd be great. If not, I'll try and get around to it ASAP.

**Comment by Fogetti** [comment]
Hi Andrew, thank you for the quick response!

I am very bad at ruby. A first grader must be better than me. :D And I have never developed any plugins for logstash, but I will take a look at it and see how far I can get. For this reason I cannot promise a PR. But we will see.

**Comment by andrewvc** [comment]
@Fogetti in that case, don't worry about it. I'll make this part of my work on #5 . Thanks for the feedback however, this will be a great addition to the plugin :)

**Comment by andrewvc** [comment]
Merged a while ago into master and released!

**Comment by Fogetti** [comment]
Thank you Andrew! Sorry for the late reply. Great to have such committed bunch of developers. I will try the changes later. :)
