### ISSUE TITLE
Drop "if @connected.get" from "publish_serialized"

### ISSUE THREAD

**Issue by ssc-** [logstash-plugins/logstash-output-rabbitmq#16]
I'm wondering why connection is checked explicitly here. Messages will be lost without any retry. If we would wait for the exception, reconnect and retry would be triggered.

See: 
```ruby
    def publish_serialized(event, message)
      begin
        if @connected.get
          @x.publish(message, :routing_key => event.sprintf(@key), :properties => { :persistent => @persistent })
        else
          @logger.warn("Tried to send a message, but not connected to RabbitMQ.")
        end
      rescue MarchHare::Exception, IOError, com.rabbitmq.client.AlreadyClosedException => e
```
https://github.com/logstash-plugins/logstash-output-rabbitmq/blob/4fb5bcabe36a10864315d9807722cdae3e91588c/lib/logstash/outputs/rabbitmq/march_hare.rb#L37-44

**Comment by andrewvc** [comment]
@ssc- I'm essentially going to rewrite this module today. Good sighting, I'll be sure to fix this behavior.

**Comment by jordansissel** [comment]
@michaelklishin has maintained this for a long time, and may be a good person to ask about things if you have questions about the rabbitmq stuff. <3

**Comment by michaelklishin** [comment]
@ssc- re-trying has always been the plan but various contributors (including myself) haven't gotten around to finish it.

@andrewvc what are the goals with the rewrite? This version of the plugin is a good couple of years old but most of the decisions in it are still relevant.

**Comment by andrewvc** [comment]
@michaelklishin my basic goal is to refactor the method structure and control flow to make the module more testable. I've got a WIP PR open on #19 . I'd greatly appreciate your review / input!

**Comment by andrewvc** [comment]
@ssc- I've changed the behavior in #19 to always retry.

**Comment by andrewvc** [comment]
Now in master!
