### ISSUE TITLE
:message=>”The error reported is: \n ”

### ISSUE THREAD

**Issue by stwomack** [logstash-plugins/logstash-output-rabbitmq#28]
I was getting this error when I was using the rabbitmq input and output plugins and NOT setting the vhost setting when required. The system account I'm using is tied to its own vhost, and I needed to provide that setting to the plugin configuration, however because of the vague error message, I had to search my rabbitmq logs to determine what was happening.

**Comment by sardetushar** [comment]
i am facing same issue . .please guide me on this

**Comment by magnusbaeck** [comment]
> i am facing same issue . .please guide me on this .. only i can see is "The error reported is: \n" .. no more logs . . note - in my case rabbitmq is connected with LDAP

As @stwomack notes his problem with that he hadn't set the `vhost` parameter as was necessary. If this isn't the case for you, please ask on http://discuss.elastic.co and give more details (like your Logstash configuration and the full error message from Logstash).
