### ISSUE TITLE
Supported exchange types

### ISSUE THREAD

**Issue by cFire** [logstash-plugins/logstash-output-rabbitmq#29]
currently only exchange types accepted are direct, fanout and topic. Would very much like to see support for at least the headers exchange type and preferably also custom exchange types like x-consistent-hash and x-modulus-hash.

**Comment by cFire** [comment]
Side note: This might also resolve/workaround issue #25 as they would be able to use the rabbitmq_sharding plugin.

**Comment by cFire** [comment]
The actual definition looks to be done in the logstash mixin:
https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection/blob/master/lib/logstash/plugin_mixins/rabbitmq_connection.rb

Should I move this issue to that repo?

**Comment by maxs** [comment]
I new to log stash and rabbitmq but need the support of headers exchange. Please advice if you has found something useful.

**Comment by andrewvc** [comment]
@maxs @cFire this change has been merged in a while ago and should now work. Closing this issue.
