### ISSUE TITLE
Plugin can't be loaded from Logstash 1.5.4 and 2.0

### ISSUE THREAD

**Issue by magnusbaeck** [logstash-plugins/logstash-output-rabbitmq#30]
It seems the loading of the rabbitmq output plugin broke in Logstash 1.5.4 when the plugin was stepped to 1.1.0 (including a step-up of march_hare from 2.5.1 to 2.11.0), a problem that doesn't appear to be fixed in the Logstash 2.0 beta. Not sure if this is a problem with the plugin or with the Logstash's packaging of it.

    $ for i in logstash_{1.5.3,1.5.4,2.0}*.deb ; do  
    > sudo dpkg -i $i > /dev/null 2>&1
    > echo =============================
    > /opt/logstash/bin/logstash --version
    > /opt/logstash/bin/plugin list | grep logstash-output-rabbitmq
    > /opt/logstash/bin/logstash --configtest -e 'output { rabbitmq { host => "localhost" exchange => "test" exchange_type => "topic" } }'
    > done
    =============================
    logstash 1.5.3
    logstash-output-rabbitmq
    Configuration OK
    =============================
    logstash 1.5.4
    logstash-output-rabbitmq
    The error reported is: 
      Couldn't find any output plugin named 'rabbitmq'. Are you sure this is correct? Trying to load the rabbitmq output plugin resulted in this error: no such file to load -- ext/rabbitmq-client
    =============================
    logstash 2.0.0-rc1
    logstash-output-rabbitmq
    The error reported is: 
      Couldn't find any output plugin named 'rabbitmq'. Are you sure this is correct? Trying to load the rabbitmq output plugin resulted in this error: no such file to load -- ext/rabbitmq-client

When downloading the tarball and running Logstash from there the problem is still there but the error message is different:

    $ logstash-2.0.0-rc1/bin/logstash -e 'output { rabbitmq { host => "localhost" exchange => "test" exchange_type => "topic" } }'
    The error reported is: 
      Couldn't find any output plugin named 'rabbitmq'. Are you sure this is correct? Trying to load the rabbitmq output plugin resulted in this error: NameError

This is on a Debian 7.9 (wheezy) system with Oracle Java 8u60

**Comment by purbon** [comment]
Thanks a lot for your report, will investigate.

**Comment by andrewvc** [comment]
@magnusbaeck thanks for reporting this. I don't have the error on 1.5.4 (OSX + Downloaded zip), but I do have it on the latest 2.0RC. I'll be investigating this today:

```
~/D/logstash-1.5.4 $ bin/logstash -e "input { generator { count => 50 } } output { rabbitmq { exchange => foo exchange_type => topic host => localhost } }"
Logstash startup completed
Logstash shutdown completed
~/D/logstash-1.5.4 $ cd ../logstash-2.0.0-rc1/
~/D/logstash-2.0.0-rc1 $ bin/logstash -e "input { generator { count => 50 } } output { rabbitmq { exchange => foo exchange_type => topic host => localhost } }"
The error reported is:
  Couldn't find any output plugin named 'rabbitmq'. Are you sure this is correct? Trying to load the rabbitmq output plugin resulted in this error: NameError
```

**Comment by andrewvc** [comment]
@magnusbaeck this has just been fixed and pushed as 3.0.5 from PR #31. Thanks for finding this bug!

**Comment by magnusbaeck** [comment]
Thanks for the quick correction! Close the issue?

**Comment by mgsh** [comment]
```
$ /opt/logstash/bin/logstash --version
logstash 2.0.0

$ /opt/logstash/bin/plugin list --verbose rabbitmq
logstash-input-rabbitmq (3.0.3)
logstash-output-rabbitmq (3.0.5)

$ /opt/logstash/bin/logstash -t -e 'input { generator { count => 10 } } output { rabbitmq { host => localhost exchange => logstash_test } }'
The error reported is: 
  Couldn't find any output plugin named 'rabbitmq'. Are you sure this is correct? Trying to load the rabbitmq output plugin resulted in this error: no such file to load -- ext/rabbitmq-client
```
I'm facing the same issue in output plugin version 3.0.5. Can you please let me know if I'm missing something here? This is on Ubuntu 14.04.3.

**Comment by mezzomondo** [comment]
Exactly the same issue also here:
```
$ cat /etc/issue
Ubuntu 14.04.3 LTS

$ /opt/logstash/bin/logstash --version
logstash 2.1.0

$ /opt/logstash/bin/plugin list --verbose rabbitmq
logstash-input-rabbitmq (3.1.1)
logstash-output-rabbitmq (3.0.6)

/opt/logstash/bin/logstash -t -e 'input { generator { count => 10 } } output { rabbitmq { host => localhost exchange => logstash_test } }'
The error reported is: 
  Couldn't find any output plugin named 'rabbitmq'. Are you sure this is correct? Trying to load the rabbitmq output plugin resulted in this error: no such file to load -- ext/rabbitmq-client
```

**Comment by jordansissel** [comment]
In Logstash 2.1.1, things are working for me:

```
% bin/plugin list --verbose | grep rabbitmq
logstash-input-rabbitmq (3.1.1)
logstash-output-rabbitmq (3.0.6)

% bin/logstash --version
logstash 2.1.1

% bin/logstash -t -e 'input { generator { count => 10 } } output { rabbitmq { host => localhost exchange => logstash_test } }'
Missing a required setting for the rabbitmq output plugin:
...
```

^^ is the rabbitmq output being loaded successfully and failing config validation because of a missing  setting. Looks OK to me.

Can you try with Logstash 2.1.1?

**Comment by mezzomondo** [comment]
I think I found the problem:

```
$ /opt/logstash/bin/logstash -t -e 'input { generator { count => 10 } } output { rabbitmq { host => localhost exchange => logstash_test } }'
The error reported is:
  Couldn't find any output plugin named 'rabbitmq'. Are you sure this is correct? Trying to load the rabbitmq output plugin resulted in this error: no such file to load -- ext/rabbitmq-client
```

But:

```
$ sudo /opt/logstash/bin/logstash -t -e 'input { generator { count => 10 } } output { rabbitmq { host => localhost exchange => logstash_test } }'
Missing a required setting for the rabbitmq output plugin:
...
```
So I should run it as root.

Thank you for your advice.

**Comment by magnusbaeck** [comment]
That's an interesting observation, but it should of course work for non-root users as well.

**Comment by andrewvc** [comment]
This seems like a weird file permissions error. @mezzomondo @magnusbaeck can you `ls -l`the rabbitmq plugin files?

Running this inside your plugin dir should give the correct output:
`find vendor/ | grep rabbitmq | xargs stat`

It looks to me that the issue is here: `16777220 30549407 -rw-r----- 1 andrewvc staff 0 417376 "Nov 26 06:48:58 2015" "Nov 24 06:42:21 2015" "Nov 26 06:49:00 2015" "Nov 24 06:42:21 2015" 4096 816 0 vendor//bundle/jruby/1.9/gems/march_hare-2.11.0-java/lib/ext/rabbitmq-client.jar`
I'm going to release an updated version of these logstash plugins to fix this issue, as well as bumping to the latest march_hare version.

**Comment by andrewvc** [comment]
I've got a fix in here. https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection/pull/13 will update this thread when we release a new gem today.

**Comment by mezzomondo** [comment]
@andrewvc same permissions here.

**Comment by andrewvc** [comment]
I've released a new gem that should fix this @magnusbaeck @mezzomondo
