### ISSUE TITLE
Published gem not compatible with Logstash 2.0-rc1-1

### ISSUE THREAD

**Issue by ceeeekay** [logstash-plugins/logstash-output-rabbitmq#33]
Logstash is unable to start when using RMQ output. Error reported is:
> Couldn't find any output plugin named 'rabbitmq'. Are you sure this is correct? Trying to load the rabbitmq output plugin resulted in this error: NameError

'plugin list' shows the plugin is present.
Installing logstash-output-rabbitmq manually completes successfully, but reports the same error on Logstash startup.

This problem has also been present with the previous 2.0 beta releases.

Can we please have a new gem pushed to fix this issue?

**Comment by suyograo** [comment]
@ceeeekay we published a version with this fix already. You can update to it by `bin/plugin install --version 3.0.5 logstash-ouput-rabbitmq`. This will be in GA release of LS though

**Comment by ceeeekay** [comment]
Thanks for the speedy response, however 'bin/plugin install --version 3.0.5 logstash-ouput-rabbitmq' results in 
> Validating logstash-ouput-rabbitmq-3.0.5
> Plugin logstash-ouput-rabbitmq version 3.0.5 does not exist
> ERROR: Installation aborted, verification failed for logstash-ouput-rabbitmq 3.0.5

Is there something I'm missing?
