### ISSUE TITLE
Plugin should rescue broken channels better

### ISSUE THREAD

**Issue by andrewvc** [logstash-plugins/logstash-output-rabbitmq#60]
Ever since this plugin switched to automatic recovery we've found situations where the automatic recovery wasn't so automatic, as in https://github.com/logstash-plugins/logstash-output-rabbitmq/issues/42#issuecomment-300896779 . We should just rescue and manually reset in those cases.

**Comment by robbavey** [comment]
Looked into this briefly - tried to reproduce by throwing https://github.com/Shopify/toxiproxy into the mix to simulate network badness, but no dice. Putting on hold for now, will pick up at a later date
