### ISSUE TITLE
Output does not respect blocked connections.

### ISSUE THREAD

**Issue by yaauie** [logstash-plugins/logstash-output-rabbitmq#85]
When a connection is blocked (e.g., RabbitMQ is unable or unwilling to consume from the underlying TCP stream), the connection is flagged and the client is notified.

March Hare allows producers to subscribe to `blocked` and `unblocked` notifications, allowing the application to apply back-pressure _before_ appending the messages to the TCP stream.

Example here: https://github.com/ruby-amqp/march_hare/blob/v3.1.1/examples/blocked_connection_notifications.rb

We should apply back-pressure when the connection is blocked, instead of continuing to push messages onto the queue.

**Comment by yaauie** [comment]
March Hare allows us to hook into change-state notifications for a connection's blocked status, but at this point I cannot find a way for this to work along-side automatic connection recovery, which is enabled by default in this plugin. 

My plan of attack was to create a blocking [`BackPressureProvider`](https://gist.github.com/yaauie/d56515e41050e83fb3cc9692268055a7) backed by a state machine, with transitions triggered by the hooks on the RabbitMQ connection. 

Connection recovery in March Hare _replaces_ the underlying connection object which has two effects:
 - our subscription to change-state notifications does not propagate to the new connection (https://github.com/ruby-amqp/march_hare/issues/141)
 - when a blocked connection is replaced by a new unblocked connection, we have no way to hook into RabbitMQ to trigger our state machine to transition back to "unblocked".

***

I think this means that in order to use a connection's blocked notifications to propagate back-pressure, we will need to eschew March Hare's automatic connection recovery in favour of a custom implementation. This is made significantly harder by the fact that the RabbitMQ Connection Mixin exposes these March Hare internals and those same internals are interacted with directly liberally by consumers.

**Comment by vanbcguy** [comment]
Anything happening on this? We're experiencing data loss on a regular basis due to this problem.

**Comment by telune** [comment]
Hi @yaauie, I see the issue you opened on the march_hare repo has been closed and, as far as I can tell, included in version 4.0.0. Does this mean that the Logstash RabbitMQ output plugin can now correctly handle blocked connections? Or do we need to wait for it to include version 4.0.0 of March Hare?

This issue is relevant for my use case, so I'd like to know if there's any advancement on this. Up to now, I resorted to replacing the RabbitMQ output with a `ruby` filter and adding an explicit `channel.wait_for_confirms` after the call to `publish`, but I'd like to use something more robust, and hopefully integrated in the RabbitMQ output.

**Comment by vanbcguy** [comment]
> Hi @yaauie, I see the issue you opened on the march_hare repo has been closed and, as far as I can tell, included in version 4.0.0. Does this mean that the Logstash RabbitMQ output plugin can now correctly handle blocked connections? Or do we need to wait for it to include version 4.0.0 of March Hare?
> 
> This issue is relevant for my use case, so I'd like to know if there's any advancement on this. Up to now, I resorted to replacing the RabbitMQ output with a `ruby` filter and adding an explicit `channel.wait_for_confirms` after the call to `publish`, but I'd like to use something more robust, and hopefully integrated in the RabbitMQ output.

The update fixed everything for us; RabbitMQ memory use has been drastically reduced and it now seems to handle blocked connections properly. If you run the logstash plugin update it'll say that it hasn't been updated, but it has actually updated the underlying libraries.

**Comment by yaauie** [comment]
While the underlying libraries have been improved, the fix to actually hook into connection blocked notifications was shipped with the [RabbitMQ Integration Plugin v7.0](https://github.com/logstash-plugins/logstash-integration-rabbitmq/blob/v7.0.0/CHANGELOG.md).

If you cannot run Logstash 6.5+ (which is required for integration plugins), please re-open or comment and I'll work to figure out a backport strategy for you.

**Comment by telune** [comment]
> While the underlying libraries have been improved, the fix to actually hook into connection blocked notifications was shipped with the [RabbitMQ Integration Plugin v7.0](https://github.com/logstash-plugins/logstash-integration-rabbitmq/blob/v7.0.0/CHANGELOG.md).
> 
> If you cannot run Logstash 6.5+ (which is required for integration plugins), please re-open or comment and I'll work to figure out a backport strategy for you.

Cool, I wasn't aware of the integration plugin! We are using Logstash 6.8.2, so we'll just need to install the `logstash-integration-rabbitmq` plugin, right? Will it be shipped by default in some future version of Logstash?
